### ISSUE TITLE
Allow user to specify URL for push instead of registry, namespace and name flags

### ISSUE THREAD

**Issue by chancez** [app-registry/helm-plugin#17]
Currently you can push using
```
helm registry push --namespace chancez-apps quay.io
```

Instead it seems like this would be better:

```
helm registry push quay.io/chancez-apps/myapp
``` 

where `myapp` may, or may not be the name in chart.yaml. This allows users to push to whichever namespace, registry, and also easily push to a repo with a different name from the chart.yaml.

**Comment by ant31** [comment]
I will let the server know about that and store both information: 
repo-name / manifest-name

```
# use name from Chart.yaml (removed the --namespace option)
helm registry push quay.io/chancez-apps   

# use repo-name instead
helm registry push quay.io/chancez-apps/repo-name

# push to another version (experimental) 
helm registry push quay.io/chancez-apps/repo-name@2.4.5
```

**Comment by ant31** [comment]
https://github.com/app-registry/appr-cli/pull/25

**Comment by chancez** [comment]
That looks great. I'll give it a try.

**Comment by gtaylor** [comment]
Will I also be able to do something like:
```
helm registry list quay.io/ant31
```
