### ISSUE TITLE
Plugin help should indicate --version does not apply and name is derived from Chart.yaml on helm charts

### ISSUE THREAD

**Issue by venezia** [app-registry/helm-plugin#28]
If you do a `helm registry push --version 1.1.1 ...` but your `Chart.yaml` specifies 0.1.2, then 0.1.2 will be the version used.

If the version cannot be overridden, why does the command line list it as an option?  It should be more clear that it will ignore this value and user the `version` value in `Chart.yaml`

Similarly I cannot (but I could be failing at googling) that the directory does not indicate the application repository name, but rather the `name` value in `Chart.yaml`

Would like to see this being more clear

**Comment by ant31** [comment]
What you describe is available on the plugin version 0.4.1:

```
$ cat Chart.yaml
apiVersion: v1
description: A Helm chart for Kubernetes
name: mynginx
version: 0.1.0
```

This the `mynginx` version 0.1.0, but you can push it to any repo name and use a different version:
```
helm registry push quay.io/alegrand/cookieapp --version 2.3.4
package: alegrand/cookieapp (2.3.4 | helm) pushed
```
This will NOT override values in the Chart.yaml !

**Comment by venezia** [comment]
I've updated to 0.4.1 (by removing the registry folder in ~/helm/plugins) and did:

```shell
venezia$ helm registry push --version 5.5.5 --namespace venezia quay.io
package: venezia/bar (0.1.2 | helm) pushed
```

Which was similar to 

But when I did it like you showed up above, it did work for me as well

```shell
venezia$ helm registry push quay.io/venezia/testing --version 2.3.4
package: venezia/testing (2.3.4 | helm) pushed
```

Maybe my problem is looking at https://coreos.com/blog/quay-application-registry-for-kubernetes.html and trying to follow that example, but either way, its curious that it would seem the flags in the former example are just silently dropped.  Would be nice to warn the user or something?

**Comment by ant31** [comment]
Thanks for your feedback. 

Yes the command line evolve from gathering comments about it. 
I'll update the Changelog to reflect better those changes and update the blogpost
