### ISSUE TITLE
Specifying chart version to install

### ISSUE THREAD

**Issue by mgoodness** [app-registry/helm-plugin#33]
Helm natively supports a `--version` argument to specify the version of a chart to install. Is there an equivalent option for the registry plugin?

`helm registry install quay.io/mgoodness/alb-ingress-controller-helm --version 0.0.3` installs the latest version available, not `0.0.3`.

**Comment by jzelinskie** [comment]
In addition to static versions like this, there's the concept of a channel which is essentially a mutable pointer to a particular version. This is essentially equivalent to docker's "latest" tag, if that makes things more concrete. You can create things like alpha/beta/stable channels and update the version they point to.

**Comment by ant31** [comment]
Oups doc got deleted, I will update the readme 
In short:  
```shell
# Install from a release version
# use @$version 
helm registry install quay.io/mgoodness/alb-ingress-controller-helm@0.0.3

# Install from a digest:  @sha256:$SHA
# list all digest
$ helm registry show quay.io/mgoodness/alb-ingress-controller-helm   
Info: mgoodness/alb-ingress-controller-helm

release    manifest                                      digest
---------  --------------------------------------------  ----------------------------------------------------------------
0.0.2      application/vnd.cnr.package.helm.v0.tar+gzip  c323f168a6aaf2699befaf57feb501a689e18b2f96e883068887da93bb14e9b2
0.0.3      application/vnd.cnr.package.helm.v0.tar+gzip  9f376dd32071e59a73a9f4d03675c4bb896b247c095a162b35eaa3209d508ec0
0.0.4      application/vnd.cnr.package.helm.v0.tar+gzip  965377c3b8700429ab3226b9eef7a7a92131fe6d6d1283d78b685ec92f8ec028

# Install 
$ helm registry install quay.io/mgoodness/alb-ingress-controller-helm@sha256:9f376dd32071e59a73a9f4d03675c4bb896b247c095a162b35eaa3209d508ec0
```

**Comment by ant31** [comment]
You may be interrested in using helm `requirements.yaml` too : 
https://github.com/app-registry/appr-helm-plugin/issues/3#issuecomment-302701693

version number should be immutable, force push is temporary allowed. A version number could be view as an alias to digest, it's important to trust what's going to be installed `@sha256:$SHA` or `@$VERSION` are equivalent.

Using mutable tags are useful in many cases too, this why we introduced channels.
A channel is a pointer to a version and the chart/package maintainer can move that pointer.
On version can be pointed by multiple channels
```
stable -> 2.4.5
beta -> 2.5.0
stable-1 -> 1.4.3
latest -> 2.5.0
```

From the CLI to use channels:
eg: 
```shell
# Associate a chart release to a channel 
$ helm registry push  quay.io/charts/gitlab-ce --channel stable
>>> Release '0.1.5' added on 'stable'
# Alternative
$ helm registry channel quay.io/charts/gitlab-ce@0.1.5 --set-release  -c dev     
>>> Release '0.1.5' added on 'dev'

# List channels
$ helm registry channel quay.io/charts/gitlab-ce       

channel    release
---------  ---------
stable     0.1.5
dev        0.1.5
```
By nature a channel is moving, to use it to install a chart the notation is `:$channel` 
```
$ helm registry install quay.io/charts/gitlab-ce:stable 
``` 

edit: https://github.com/app-registry/appr/blob/master/Documentation/quick-start.md

**Comment by mgoodness** [comment]
Excellent, thanks guys! I definitely plan to explore channels, and the support for dependencies is quite welcome.

Feel free to close once the appropriate docs are updated.

**Comment by ant31** [comment]
doc: https://github.com/app-registry/appr/blob/master/Documentation/quick-start.md#pull--download--install
