### ISSUE TITLE
helm registry install does not seem to support specifying values

### ISSUE THREAD

**Issue by jschrantz** [app-registry/helm-plugin#35]
Helm install supports the following parameters:

```
--set stringArray        set values on the command line (can specify multiple or separate values with commas: key1=val1,key2=val2)
-f, --values valueFiles      specify values in a YAML file (can specify multiple) (default [])
```

Helm registry install doesn't seem to support equivalent parameters.

Ideally charts stored in an appr registry would be usable directly from helm install, but until that functionality is available in helm (mentioned in [kubernetes/helm#2447](https://github.com/kubernetes/helm/issues/2447#issuecomment-318527603)) helm registry install should be able to support configuring a release during deployment.

**Comment by jzelinskie** [comment]
IIRC using a standalone `--` designates that any following flags will be passed to Helm.
So you should be able to do something like:
`helm registry install quay.io/jzelinskie/chihaya-helm:v0.1.0 -- -f values.yaml`

**Comment by jschrantz** [comment]
Thanks @jzelinskie, that does seem to work.

It might be worth throwing into the usage string, because I couldn't find anything through the CLI or in the README indicating as much.

**Comment by ant31** [comment]
@jschrantz yes, it's a general issue about documentation. 
I'll work on that soon, at least to expose most usage. 

in latest version `--` separation should not even be required,

**Comment by ant31** [comment]
I updated (v0.7.3) he usage / help messages to include example using helm flags: 
  
```
appr helm install --help
usage: appr helm install [-h] [-k] [--cacert CACERT] [-v VERSION]
                         [--dest DEST]
                         package

Fetch a Chart from the app-registry and execute `helm install`.
Helm's options can be passed on the command:
$ appr helm install [APPR_OPTS] -- [HELM_OPTS]
$ appr helm install quay.io/ant31/cookieapp -- --set imageTag=v0.4.5 --namespace demo

positional arguments:
  package               package-name

optional arguments:
  -h, --help            show this help message and exit
  -k, --insecure        turn off verification of the https certificate
  --cacert CACERT       CA certificate to verify peer against (SSL)
  -v VERSION, --version VERSION
                        package VERSION
  --dest DEST           directory used to extract resources

helm options:
  See 'helm install --help'
```
