### ISSUE TITLE
Allow user to select in which namespace the chart will be deployed

### ISSUE THREAD

**Issue by kdihalas** [app-registry/helm-plugin#36]
User should be able to choose in which namespace the chart will be deployed. Helm has this build in with the flag --namespace.

**Comment by jeff-knurek** [comment]
this works for me...
`helm registry install quay.io/charts/kube-lego --namespace works --name test`

```
$ helm registry version quay.io
Api-version: {u'cnr-api': u'0.2.7'}
Client-version: 0.6.1
```

```
$ helm list
NAME         	REVISION	UPDATED                 	STATUS  	CHART          	NAMESPACE
test         	1       	Tue Aug 29 14:51:06 2017	DEPLOYED	kube-lego-0.1.8	works
```
```
$ kubectl get ns
NAME          STATUS    AGE
default       Active    42d
kube-public   Active    42d
kube-system   Active    42d
works         Active    20s
```

**Comment by jzelinskie** [comment]
You can separate appr flags from Helm flags with `--`:

```
$ helm registry install quay.io/charts/kube-lego -- -f values.yaml
```

where -f is the Helm flag, not an app registry one

**Comment by ant31** [comment]
@kdihalas which version are you using ? with latest it should work. 
see also #35.

Can we close?

**Comment by kdihalas** [comment]
Sorry for the delay, the provided example seems to work.

thanks for the help
