### ISSUE TITLE
Cannot download appr anymore

### ISSUE THREAD

**Issue by venezia** [app-registry/helm-plugin#38]
It used to be that you could unpack the `appr-helm-plugin` release into `~/.helm/plugins` (thus creating `~/.helm/plugins/registry` folder, and run `helm registry list quay.io` upon which the plugin would realize appr was not downloaded and fetch it for you.

This doesn't seem to work anymore.

```
$ helm registry list quay.io
Registry plugin assets do not exist, download them now !
downloading https://github.com/app-registry/appr/releases/download/v0.7.2/appr-osx-x64 ...
Traceback (most recent call last):
  File "PyInstaller/loader/rthooks/pyi_rth_multiprocessing.py", line 9, in <module>
ImportError: No module named spawn
[8122] Failed to execute script pyi_rth_multiprocessing
Error: plugin "registry" exited with error
```

Did something change?

**Comment by ant31** [comment]
is  0.7.1 working on osx ?

Le 16 août 2017 22:59, "Michael Venezia" <notifications@github.com> a
écrit :

**Comment by venezia** [comment]
You're right, 0.7.1 works, but not 0.7.2

**Comment by xh3b4sd** [comment]
I am running into this right now. How to make helm take 0.7.1 instead of the broken version?

**Comment by ant31** [comment]
it should be
`helm registry upgrade-plugin $tag`
or manually download the bin in the plugin directory

**Comment by xh3b4sd** [comment]
Thanks. For the record, I fixed it for me using this. 

```
helm registry upgrade-plugin v0.7.1
```

The tags are prefixed with `v`. Upgrading using `0.7.1` seemed to work but resulted in the `appr` file to contain `Not found`. The golden path for the user and the error handling could use some love here.

**Comment by ant31** [comment]
0.7.3 should fix this, can you confirm ? 
Issue came from pyinstaller (https://github.com/pyinstaller/pyinstaller/issues/2759).

Thanks
