### ISSUE TITLE
appr 0.7.2 does not work on OSX

### ISSUE THREAD

**Issue by munnerz** [app-registry/helm-plugin#39]
I've just set up this plugin with Helm using the latest versions of both (0.5.1 of this repo, and 0.7.2 of appr) and receive this error:

```
➜  project git:(master) helm registry version <repo address>
Traceback (most recent call last):
  File "PyInstaller/loader/rthooks/pyi_rth_multiprocessing.py", line 9, in <module>
ImportError: No module named spawn
[49710] Failed to execute script pyi_rth_multiprocessing
Error: plugin "registry" exited with error
```

This issue persists after running `pip install spawn` and `pip3 install spawn`.

Installing with appr 0.7.1 has fixed the issue. I'm not sure if this is best to be reported on the `appr` repository itself, or here.

**Comment by ant31** [comment]
Hi, thx for report. 
it seems related to a bug with pyinstaller, it should be fixed on its master. I ll add tests to check the artifacts

**Comment by gankit** [comment]
I'm running into this also. Just cloned from master.

**Comment by ant31** [comment]
0.7.3 should fix this, can you confirm ? 
Issue came from pyinstaller (https://github.com/pyinstaller/pyinstaller/issues/2759).
