### ISSUE TITLE
How to login robot accounts?

### ISSUE THREAD

**Issue by naveensrinivasan** [app-registry/helm-plugin#9]
I am trying to use robot account to login to quay.io to push the helm chart into repo. 
When I tried something like this
`helm registry login -u upskill+push_bot -p abc` 

it failed `cnr: error: 401 Client Error: UNAUTHORIZED for url: https://quay.io/cnr/api/v1/users/login`

How do I use a robot account to do this?

Thanks

**Comment by naveensrinivasan** [comment]
@ant31 @philips  Any update on this? I would like to know how to login to quay using robot account to pull applications?

**Comment by ant31** [comment]
@naveensrinivasan thanks to report this issue 
We are working on it and we will update quay.io to accept robot account from the registry plugin. 
I'll let you know as soon as it's available.

**Comment by naveensrinivasan** [comment]
@ant31 Thanks for the update.

**Comment by ant31** [comment]
@naveensrinivasan it's fixed and deployed
```
helm registry login -u "ant31+ant31testrobot" -p "$ROBOT_TOKEN"  quay.io
 >>> Login succeeded
```
Thank you
